name: Purge Cloudflare Cache

on:
  push:
    branches: [ main ]  

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare cache
        uses: nathanvaughn/actions-cloudflare-purge@v4.0.0
        with:
          cf_zone: ${{ secrets.CF_ZONE_ID }}
          cf_auth: ${{ secrets.CF_API_TOKEN }}
